### ISSUE TITLE
"Demand shaping" definition within Glossary's Useful Terms.

### ISSUE THREAD

**Issue by raymundovr** [Green-Software-Foundation/learn#169] opened 2023-04-05 05:33 UTC
**Describe the bug**
Within the Glossary there's a Useful Terms section that lists some concepts, one of the is "Demand Shaping" which is currently defined as:
```
Demand shaping - The strategy of moving workloads to regions or times when the carbon intensity is less
```

This current definition matches "Demand Shifting" more accurately.

From the "Demand Shaping" section, we learn that

```
Demand shaping is a similar strategy. However, instead of moving demand to a different region or time, we shape our computation to match the existing supply.
```
**To Reproduce**

1. Go to Glossary
3. Scroll down to Useful Terms

**Expected behavior**

A better definition of Demand Shaping.
Example:
```
Demand Shaping - The strategy of performing more or less computation depending on the current carbon intensity.
```

In addition, the inclusion of a definition for "Demand Shifting" within the "Useful Terms" can also be considered so that they can be compared by the reader.

**Desktop (please complete the following information):**
 - OS: Mac OS Ventura
 - Browser: Firefox
 - Version: 111.0.1

**Comment by greenhsu123** [comment] 2023-05-11 09:23
Great spot, thanks for flagging! The issue is fixed now.

**Closed by greenhsu123** 2023-05-11 09:23 UTC

**Comment by raymundovr** [comment] 2023-05-11 11:48
Thank you @greenhsu123
